### ISSUE TITLE
Stopped working on Alfred 4

### ISSUE THREAD

**Issue by Madd0g** [deanishe/alfred-repos#20]
Getting this in the log whenever I try to bring up the workflow (it worked yesterday and I made no major changes)

```log
11:29:45 workflow.py:2061 DEBUG    ---------- Git Repos (2.1.2) ----------
11:29:45 workflow.py:1468 DEBUG    reading settings from /Users/myuser/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-git-repos/settings.json
11:29:45 workflow.py:2343 DEBUG    update check not due
11:29:45 workflow.py:2225 DEBUG    last run version: 2.1.2
11:29:45 repos.py:341 DEBUG    args={'<appkey>': None,
 '<path>': None,
 '<query>': u'',
 'open': False,
 'search': True,
 'settings': False,
 'update': False}
11:29:45 repos.py:357 DEBUG    opts={'do_update': False, 'appkey': 'default', 'do_settings': False, 'do_open': False, 'do_search': True, 'query': u'', 'path': None, 'update_interval': 10800}
11:29:45 workflow.py:1695 DEBUG    loading cached data: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/__workflow_latest_version.cpickle
11:29:45 workflow.py:1695 DEBUG    loading cached data: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/__workflow_update_status.cpickle
11:29:45 workflow.py:2080 ERROR    'version'
Traceback (most recent call last):
  File "/Users/myuser/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D3DF97C-1C49-437B-ADD2-79FA2222B328/workflow/workflow.py", line 2073, in run
    func(self)
  File "repos.py", line 383, in main
    v = wf.cached_data('__workflow_update_status', max_age=0)['version']
KeyError: 'version'
```

**Comment by deanishe** [comment]
Try clearing the cache by entering `repos workflow:delcache` into Alfred.

**Comment by Madd0g** [comment]
getting a new error now:

```
11:46:17 workflow.py:2061 DEBUG    ---------- Git Repos (2.1.2) ----------
11:46:17 workflow.py:1468 DEBUG    reading settings from /Users/myuser/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-git-repos/settings.json
11:46:17 workflow.py:2343 DEBUG    update check not due
11:46:17 workflow.py:2225 DEBUG    last run version: 2.1.2
11:46:17 repos.py:341 DEBUG    args={'<appkey>': None,
 '<path>': None,
 '<query>': u'',
 'open': False,
 'search': True,
 'settings': False,
 'update': False}
11:46:17 repos.py:357 DEBUG    opts={'do_update': False, 'appkey': 'default', 'do_settings': False, 'do_open': False, 'do_search': True, 'query': u'', 'path': None, 'update_interval': 10800}
11:46:17 workflow.py:1695 DEBUG    loading cached data: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/__workflow_latest_version.cpickle
11:46:17 workflow.py:2080 ERROR    'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/myuser/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D3DF97C-1C49-437B-ADD2-79FA2222B328/workflow/workflow.py", line 2073, in run
    func(self)
  File "repos.py", line 383, in main
    v = wf.cached_data('__workflow_update_status', max_age=0)['version']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by deanishe** [comment]
Is this actually the log, or is it from Alfred's debugger? They're not the same thing. Please make sure you're posting the contents of the log file (open it with `repos workflow:openlog`).

**Comment by Madd0g** [comment]
It's from Alfred's debugger, but the log shows pretty much the same info:

```
15:34:45 workflow.py:2080 ERROR    'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/myuser/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D3DF97C-1C49-437B-ADD2-79FA2222B328/workflow/workflow.py", line 2073, in run
    func(self)
  File "repos.py", line 383, in main
    v = wf.cached_data('__workflow_update_status', max_age=0)['version']
TypeError: 'NoneType' object has no attribute '__getitem__'
15:34:45 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/alfred-repos/issues
```

**Comment by deanishe** [comment]
That's not where the problem is happening. I need the log from the update.

Please clear the cache again, run the workflow until you get the error, and then post the whole log.

**Comment by Madd0g** [comment]
Hope I did it correctly, I opened and cleared the log, then cleared the cache, then tried to open the workflow:

```
01:31:39 workflow.py:2338 INFO     checking for update ...
01:31:39 update.py:406 INFO     retrieving releases for 'deanishe/alfred-repos' ...
01:31:39 background.py:225 INFO     [update] job already running
01:31:40 workflow.py:2338 INFO     checking for update ...
01:31:40 background.py:225 INFO     [__workflow_update_check] job already running
01:31:40 background.py:225 INFO     [update] job already running
01:31:40 background.py:225 INFO     [update] job already running
01:31:40 update.py:474 INFO     15 download(s) for deanishe/alfred-repos
01:31:40 update.py:140 INFO     102 repo(s) found in 0.82s
01:31:40 update.py:141 INFO     update finished
01:31:40 workflow.py:2080 ERROR    'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/myuser/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D3DF97C-1C49-437B-ADD2-79FA2222B328/workflow/workflow.py", line 2073, in run
    func(self)
  File "repos.py", line 383, in main
    v = wf.cached_data('__workflow_update_status', max_age=0)['version']

```

**Comment by deanishe** [comment]
Sorry, please do it with Alfred's debugger open to trigger debug mode. Still post the contents of the log file, *not* the debugger, though.

**Comment by Madd0g** [comment]
here it is:

```
11:44:06 workflow.py:2061 DEBUG    ---------- Git Repos (2.1.2) ----------
11:44:06 workflow.py:1468 DEBUG    reading settings from /Users/myuser/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-git-repos/settings.json
11:44:06 workflow.py:2338 INFO     checking for update ...
11:44:06 background.py:233 DEBUG    [__workflow_update_check] command cached: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/__workflow_update_check.argcache
11:44:06 background.py:237 DEBUG    [__workflow_update_check] passing job to background runner: [u'/usr/bin/python', '/Users/myuser/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D3DF97C-1C49-437B-ADD2-79FA2222B328/workflow/background.pyc', u'__workflow_update_check']
11:44:06 workflow.py:2061 DEBUG    ---------- Git Repos (2.1.2) ----------
11:44:06 background.py:243 DEBUG    [__workflow_update_check] background job started
11:44:06 workflow.py:2225 DEBUG    last run version: 2.1.2
11:44:06 repos.py:341 DEBUG    args={'<appkey>': None,
 '<path>': None,
 '<query>': u'',
 'open': False,
 'search': True,
 'settings': False,
 'update': False}
11:44:06 repos.py:357 DEBUG    opts={'do_update': False, 'appkey': 'default', 'do_settings': False, 'do_open': False, 'do_search': True, 'query': u'', 'path': None, 'update_interval': 10800}
11:44:06 repos.py:131 DEBUG    cache_age=0.00, settings_age=31872393.64
11:44:06 background.py:233 DEBUG    [update] command cached: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/update.argcache
11:44:06 background.py:280 DEBUG    [__workflow_update_check] running command: [u'/usr/bin/python', '/Users/myuser/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D3DF97C-1C49-437B-ADD2-79FA2222B328/workflow/update.py', u'check', 'deanishe/alfred-repos', '2.1.2']
11:44:06 background.py:237 DEBUG    [update] passing job to background runner: [u'/usr/bin/python', '/Users/myuser/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D3DF97C-1C49-437B-ADD2-79FA2222B328/workflow/background.pyc', 'update']
11:44:06 workflow.py:2061 DEBUG    ---------- Git Repos (2.1.2) ----------
11:44:06 update.py:406 INFO     retrieving releases for 'deanishe/alfred-repos' ...
11:44:06 background.py:243 DEBUG    [update] background job started
11:44:06 background.py:225 INFO     [update] job already running
11:44:06 workflow.py:2254 DEBUG    set last run version: 2.1.2
11:44:06 workflow.py:2103 DEBUG    ---------- finished in 0.205s ----------
11:44:06 background.py:280 DEBUG    [update] running command: ['/usr/bin/python', 'update.py']
11:44:06 workflow.py:2061 DEBUG    ---------- Git Repos (2.1.2) ----------
11:44:06 workflow.py:1468 DEBUG    reading settings from /Users/myuser/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-git-repos/settings.json
11:44:07 workflow.py:1730 DEBUG    cached data: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/github-releases-deanishe-alfred-repos.cpickle
11:44:07 update.py:474 INFO     15 download(s) for deanishe/alfred-repos
11:44:07 update.py:434 DEBUG    latest version: 3.0.0 (Git-Repos-3.0.0.alfred4workflow)
11:44:07 update.py:483 DEBUG    latest=Version('3.0.0'), installed=Version('2.1.2')
11:44:07 workflow.py:1730 DEBUG    cached data: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/__workflow_latest_version.cpickle
11:44:07 background.py:289 DEBUG    [__workflow_update_check] job complete
11:44:07 workflow.py:1468 DEBUG    reading settings from /Users/myuser/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-git-repos/settings.json
11:44:07 workflow.py:2254 DEBUG    set last run version: 2.1.2
11:44:07 workflow.py:2103 DEBUG    ---------- finished in 0.730s ----------
11:44:07 workflow.py:2061 DEBUG    ---------- Git Repos (2.1.2) ----------
11:44:07 workflow.py:1468 DEBUG    reading settings from /Users/myuser/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-git-repos/settings.json
11:44:07 workflow.py:2343 DEBUG    update check not due
11:44:07 workflow.py:2225 DEBUG    last run version: 2.1.2
11:44:07 repos.py:341 DEBUG    args={'<appkey>': None,
 '<path>': None,
 '<query>': u'',
 'open': False,
 'search': True,
 'settings': False,
 'update': False}
11:44:07 repos.py:357 DEBUG    opts={'do_update': False, 'appkey': 'default', 'do_settings': False, 'do_open': False, 'do_search': True, 'query': u'', 'path': None, 'update_interval': 10800}
11:44:07 workflow.py:1695 DEBUG    loading cached data: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/__workflow_latest_version.cpickle
11:44:07 workflow.py:2080 ERROR    'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/myuser/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D3DF97C-1C49-437B-ADD2-79FA2222B328/workflow/workflow.py", line 2073, in run
    func(self)
  File "repos.py", line 383, in main
    v = wf.cached_data('__workflow_update_status', max_age=0)['version']
TypeError: 'NoneType' object has no attribute '__getitem__'
11:44:07 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/alfred-repos/issues
11:44:07 workflow.py:2103 DEBUG    ---------- finished in 0.006s ----------
11:44:07 update.py:91 DEBUG    103 repo(s) found in `/Users/myuser/Code` in 0.78s
11:44:07 update.py:94 DEBUG        Repo(name=u'some-project', path=u'/Users/myuser/Code/some-project')
     ........ snipped my projects, bunch of lines like the one above this .........
11:44:07 workflow.py:1730 DEBUG    cached data: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/repos.cpickle
11:44:07 update.py:140 INFO     103 repo(s) found in 0.82s
11:44:07 update.py:141 INFO     update finished
11:44:07 workflow.py:2254 DEBUG    set last run version: 2.1.2
11:44:07 workflow.py:2103 DEBUG    ---------- finished in 0.825s ----------
11:44:07 background.py:289 DEBUG    [update] job complete
11:44:07 workflow.py:1468 DEBUG    reading settings from /Users/myuser/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-git-repos/settings.json
11:44:07 workflow.py:2254 DEBUG    set last run version: 2.1.2
11:44:07 workflow.py:2103 DEBUG    ---------- finished in 0.983s ----------

```

**Comment by deanishe** [comment]
Can you [install the latest version](https://github.com/deanishe/alfred-repos/releases/tag/v3.0.0), clear the cache and see if that works?

**Comment by Madd0g** [comment]
Yeah it works. Thanks
