### ISSUE TITLE
Error with v3.1

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-repos#28]
Get this error trying to run `git` command and search for repos

```bash
[02:58:26.599] Git Repos[External] Processing complete
[02:58:26.607] Git Repos[External] Passing output '' to Script Filter
[02:58:26.659] Git Repos[Script Filter] Queuing argument ''
[02:58:26.821] Git Repos[Script Filter] Script with argv '' finished
[02:58:26.825] ERROR: Git Repos[Script Filter] Code 1: .
02:58:26 workflow.py:2061 DEBUG    ---------- Git Repos (3.1.0) ----------
02:58:26 workflow.py:1468 DEBUG    reading settings from /Users/nikivi/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-git-repos/settings.json
02:58:26 workflow.py:2343 DEBUG    update check not due
02:58:26 workflow.py:2225 DEBUG    last run version: 3.1.0
02:58:26 workflow.py:2225 DEBUG    last run version: 3.1.0
02:58:26 repos.py:356 DEBUG    args={'<appkey>': None,
 '<path>': None,
 '<query>': u'',
 'open': False,
 'search': True,
 'settings': False,
 'update': False}
02:58:26 repos.py:372 DEBUG    opts={'do_update': False, 'appkey': 'default', 'do_settings': False, 'do_open': False, 'do_search': True, 'query': u'', 'path': None, 'update_interval': 10800}
02:58:26 workflow.py:1695 DEBUG    loading cached data: /Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/__workflow_latest_version.cpickle
02:58:26 repos.py:140 DEBUG    cache_age=66.22, settings_age=120.48
02:58:26 workflow.py:1695 DEBUG    loading cached data: /Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-git-repos/repos.cpickle
02:58:26 workflow.py:2080 ERROR    object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.53A60B7D-F1C9-4770-AE30-22638A0FA4F7/workflow/workflow.py", line 2073, in run
    func(self)
  File "repos.py", line 443, in main
    return do_search(repos, opts)
  File "repos.py", line 303, in do_search
    subtitles[key] = 'Open in {}'.format(join_english(app))
  File "repos.py", line 149, in join_english
    if len(items) == 1:
TypeError: object of type 'NoneType' has no len()
02:58:26 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/alfred-repos/issues
02:58:26 workflow.py:2103 DEBUG    ---------- finished in 0.006s ----------
[02:58:26.827] Git Repos[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "object of type 'NoneType' has no len()",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Git Repos'"
    }
  ]
}
```

Not too sure why it happens.

My config:

```json
{
  "__workflow_last_version": "3.1.0", 
  "app_alt": "Safari", 
  "app_cmd": "iTerm", 
  "app_ctrl": "GitHub release", 
  "app_default": "Visual Studio Code - Insiders", 
  "app_fn": "Sublime Text", 
  "app_shift": null, 
  "global_exclude_patterns": [], 
  "search_dirs": [
    {
      "depth": 4, 
      "excludes": [
        "*/src/clones/*", 
        "*/src/curated/*"
      ], 
      "path": "~/src"
    }, 
    {
      "depth": 3, 
      "path": "~/go/src/github.com/nikitavoloboev"
    }, 
    {
      "path": "~/.dotfiles/"
    }
  ]
}
```

I did run `reposupdate` beforehand.

**Comment by deanishe** [comment]
Huh. Try removing this line: `"app_shift": null,`

**Comment by nikitavoloboev** [comment]
Perfect, that worked. It did work in previous version so something did change. :)

**Comment by deanishe** [comment]
> not sure if it's a bug. :)

It's a regression, in any case.
