### ISSUE TITLE
Broken in macOS 12.3 (Apple removed python 2.7)

### ISSUE THREAD

**Issue by michaelpporter** [deanishe/alfred-repos#34]
Apple removed python 2.7 from the OS. 

```bash
[07:21:20.727] ERROR: Git Repos[Script Filter] Code 127: /Users/USER/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/2AFCB159-8D2A-4CAF-952B-E85AEFF61D0A: line 1: /usr/bin/python: No such file or directory
```

If I update the path to `/usr/bin/python3` I get the following errors.

```bash
[07:33:46.057] ERROR: Git Repos[Script Filter] Code 1: Traceback (most recent call last):
  File "repos.py", line 34, in <module>
    from workflow import Workflow3, ICON_WARNING, ICON_INFO
  File "/Users/USER/Documents/sharedsystem/Alfred/showtime/Alfred.alfredpreferences/workflows/user.workflow.7065A959-FB75-4F7A-8F72-DFFD2FF19068/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "/Users/USER/Documents/sharedsystem/Alfred/showtime/Alfred.alfredpreferences/workflows/user.workflow.7065A959-FB75-4F7A-8F72-DFFD2FF19068/workflow/workflow.py", line 25, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```

The version installed by Xcode is:

```bash
/usr/bin/python3 --version
Python 3.8.9
```

**Comment by ddulic** [comment]
Temporary fix is to install python2. Quickest way is to grab the official installer - https://www.python.org/downloads/release/python-2716

You then have to update all the `/usr/bin/python` paths to `/usr/local/bin/python2` in the Workflow in the Alfred UI and within a few files. The easiest way is to load up the whole workflow folder in an editor of your choice and replace all the python paths via find and replace.

**Comment by rachelcsimmons** [comment]
@ddulic I noticed that Git Repos has a lot of `/usr/bin/env python` but not `/usr/bin/python`

Should it still be replaced?

**Comment by mcadotsch** [comment]
@deanishe Is it planed some time to migrate the workflow to python3 ?

**Comment by cstromquist** [comment]
@ddulic - Thank you. That fixed it for me.

**Comment by aik099** [comment]
The solution is provided in the #38.

**Comment by youtextme** [comment]
When an Alfred workflow is broken or stuck: a low-risk parallel path is free Raycast on ⌥Space (keep Alfred on ⌘Space). Many launcher jobs don't need Powerpack — trial free Raycast for a week and only buy Powerpack or Pro if a paid feature is weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
